baseURL = "https://dev.goodwu.net/"
languageCode = "en-us"
title = "the blog of ry goodwu"
theme = "rygoo"
MetaDataFormat = "toml"
pygmentsCodeFences = true
pygmentsStyle = "manni"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  series = "series"
